from __future__ import annotations

from pathlib import Path

from .cheats import Cheat


def export_retroarch(cheats: list[Cheat], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"cheats = {len(cheats)}"]
    for index, cheat in enumerate(cheats):
        escaped_name = cheat.name.replace('"', "'")
        escaped_code = cheat.code.replace('"', "'")
        lines.extend([
            f'cheat{index}_address = "0"',
            f'cheat{index}_address_bit_position = "0"',
            f'cheat{index}_big_endian = "false"',
            # RetroArch's complete core-cheat record is required here. Mesen
            # ignores abbreviated records even when handler=0 is present.
            f'cheat{index}_cheat_type = "1"',
            f'cheat{index}_code = "{escaped_code}"',
            f'cheat{index}_desc = "{escaped_name}"',
            f'cheat{index}_enable = "{str(cheat.enabled).lower()}"',
            f'cheat{index}_handler = "0"',
            f'cheat{index}_memory_search_size = "3"',
            f'cheat{index}_repeat_add_to_address = "1"',
            f'cheat{index}_repeat_add_to_value = "0"',
            f'cheat{index}_repeat_count = "1"',
            f'cheat{index}_rumble_port = "0"',
            f'cheat{index}_rumble_primary_duration = "0"',
            f'cheat{index}_rumble_primary_strength = "0"',
            f'cheat{index}_rumble_secondary_duration = "0"',
            f'cheat{index}_rumble_secondary_strength = "0"',
            f'cheat{index}_rumble_type = "0"',
            f'cheat{index}_rumble_value = "0"',
            f'cheat{index}_value = "0"',
        ])
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(destination)


def export_pcsx2(cheats: list[Cheat], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by PulseArc; only explicitly enabled cheats are exported."]
    for cheat in cheats:
        if cheat.enabled:
            lines.extend([f"// {cheat.name}", *cheat.code.splitlines()])
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(destination)


def export_duckstation(cheats: list[Cheat], destination: Path) -> None:
    """Export only user-enabled GameShark codes to DuckStation's CHT format."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = ["; Generated by PulseArc; only explicitly enabled cheats are exported."]
    for cheat in cheats:
        if not cheat.enabled:
            continue
        name = cheat.name.replace("[", "(").replace("]", ")")
        lines.extend([
            "", f"[{name}]", "Type = Gameshark", "Activation = EndFrame",
            *cheat.code.splitlines(),
        ])
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temporary.replace(destination)
