#!/usr/bin/env bash
set -euo pipefail

root="$HOME/.local/opt/vlc"
export LD_LIBRARY_PATH="$root/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export VLC_PLUGIN_PATH="$root/usr/lib/vlc/plugins"
exec "$root/usr/bin/vlc" "$@"
