d /run/pulsearc 0775 root gamer -
d /run/media/gamer 0755 gamer gamer -
d /var/lib/pulsearc 0775 gamer gamer -
d /var/lib/pulsearc/library 0755 gamer gamer -
d /var/lib/pulsearc/artwork 0755 gamer gamer -

